export interface City {
  name: string
  region: string
}

export interface CountryData {
  popularCities: string[]
  allCities: City[]
}

export const CITY_DATA: Record<string, CountryData> = {
  in: {
    popularCities: [
      'Delhi NCR', 'Mumbai', 'Bengaluru', 'Hyderabad',
      'Chennai', 'Kolkata', 'Pune', 'Ahmedabad',
      'Chandigarh', 'Goa', 'Jaipur', 'Lucknow',
    ],
    allCities: [
      { name: 'Abohar', region: 'Punjab' },
      { name: 'Abu Road', region: 'Rajasthan' },
      { name: 'Adilabad', region: 'Telangana' },
      { name: 'Agartala', region: 'Tripura' },
      { name: 'Agra', region: 'Uttar Pradesh' },
      { name: 'Ahmedabad', region: 'Gujarat' },
      { name: 'Ahmednagar', region: 'Maharashtra' },
      { name: 'Aizawl', region: 'Mizoram' },
      { name: 'Ajmer', region: 'Rajasthan' },
      { name: 'Akbarpur', region: 'Uttar Pradesh' },
      { name: 'Akola', region: 'Maharashtra' },
      { name: 'Aligarh', region: 'Uttar Pradesh' },
      { name: 'Alwar', region: 'Rajasthan' },
      { name: 'Ambala', region: 'Haryana' },
      { name: 'Amravati', region: 'Maharashtra' },
      { name: 'Amritsar', region: 'Punjab' },
      { name: 'Anand', region: 'Gujarat' },
      { name: 'Anantapur', region: 'Andhra Pradesh' },
      { name: 'Asansol', region: 'West Bengal' },
      { name: 'Aurangabad', region: 'Maharashtra' },
      { name: 'Baharampur', region: 'West Bengal' },
      { name: 'Bareilly', region: 'Uttar Pradesh' },
      { name: 'Bathinda', region: 'Punjab' },
      { name: 'Begusarai', region: 'Bihar' },
      { name: 'Bengaluru', region: 'Karnataka' },
      { name: 'Bhagalpur', region: 'Bihar' },
      { name: 'Bharatpur', region: 'Rajasthan' },
      { name: 'Bhavnagar', region: 'Gujarat' },
      { name: 'Bhilai', region: 'Chhattisgarh' },
      { name: 'Bhilwara', region: 'Rajasthan' },
      { name: 'Bhopal', region: 'Madhya Pradesh' },
      { name: 'Bhubaneswar', region: 'Odisha' },
      { name: 'Bikaner', region: 'Rajasthan' },
      { name: 'Bilaspur', region: 'Chhattisgarh' },
      { name: 'Bokaro', region: 'Jharkhand' },
      { name: 'Chandigarh', region: 'Chandigarh' },
      { name: 'Chennai', region: 'Tamil Nadu' },
      { name: 'Coimbatore', region: 'Tamil Nadu' },
      { name: 'Cuttack', region: 'Odisha' },
      { name: 'Darbhanga', region: 'Bihar' },
      { name: 'Davangere', region: 'Karnataka' },
      { name: 'Dehradun', region: 'Uttarakhand' },
      { name: 'Delhi NCR', region: 'Delhi' },
      { name: 'Dhanbad', region: 'Jharkhand' },
      { name: 'Dharwad', region: 'Karnataka' },
      { name: 'Durgapur', region: 'West Bengal' },
      { name: 'Eluru', region: 'Andhra Pradesh' },
      { name: 'Erode', region: 'Tamil Nadu' },
      { name: 'Faridabad', region: 'Haryana' },
      { name: 'Farrukhabad', region: 'Uttar Pradesh' },
      { name: 'Fatehpur', region: 'Uttar Pradesh' },
      { name: 'Firozabad', region: 'Uttar Pradesh' },
      { name: 'Gandhinagar', region: 'Gujarat' },
      { name: 'Gaya', region: 'Bihar' },
      { name: 'Ghaziabad', region: 'Uttar Pradesh' },
      { name: 'Goa', region: 'Goa' },
      { name: 'Gorakhpur', region: 'Uttar Pradesh' },
      { name: 'Gulbarga', region: 'Karnataka' },
      { name: 'Guntur', region: 'Andhra Pradesh' },
      { name: 'Gurgaon', region: 'Haryana' },
      { name: 'Guwahati', region: 'Assam' },
      { name: 'Gwalior', region: 'Madhya Pradesh' },
      { name: 'Hapur', region: 'Uttar Pradesh' },
      { name: 'Haridwar', region: 'Uttarakhand' },
      { name: 'Hisar', region: 'Haryana' },
      { name: 'Hubli', region: 'Karnataka' },
      { name: 'Hyderabad', region: 'Telangana' },
      { name: 'Imphal', region: 'Manipur' },
      { name: 'Indore', region: 'Madhya Pradesh' },
      { name: 'Itanagar', region: 'Arunachal Pradesh' },
      { name: 'Jabalpur', region: 'Madhya Pradesh' },
      { name: 'Jaipur', region: 'Rajasthan' },
      { name: 'Jalandhar', region: 'Punjab' },
      { name: 'Jalgaon', region: 'Maharashtra' },
      { name: 'Jammu', region: 'Jammu & Kashmir' },
      { name: 'Jamnagar', region: 'Gujarat' },
      { name: 'Jamshedpur', region: 'Jharkhand' },
      { name: 'Jhansi', region: 'Uttar Pradesh' },
      { name: 'Jodhpur', region: 'Rajasthan' },
      { name: 'Kakinada', region: 'Andhra Pradesh' },
      { name: 'Kalyan', region: 'Maharashtra' },
      { name: 'Kanpur', region: 'Uttar Pradesh' },
      { name: 'Karimnagar', region: 'Telangana' },
      { name: 'Kochi', region: 'Kerala' },
      { name: 'Kohima', region: 'Nagaland' },
      { name: 'Kolhapur', region: 'Maharashtra' },
      { name: 'Kolkata', region: 'West Bengal' },
      { name: 'Kollam', region: 'Kerala' },
      { name: 'Kota', region: 'Rajasthan' },
      { name: 'Kozhikode', region: 'Kerala' },
      { name: 'Kurnool', region: 'Andhra Pradesh' },
      { name: 'Latur', region: 'Maharashtra' },
      { name: 'Lucknow', region: 'Uttar Pradesh' },
      { name: 'Ludhiana', region: 'Punjab' },
      { name: 'Madurai', region: 'Tamil Nadu' },
      { name: 'Malda', region: 'West Bengal' },
      { name: 'Mangalore', region: 'Karnataka' },
      { name: 'Mathura', region: 'Uttar Pradesh' },
      { name: 'Meerut', region: 'Uttar Pradesh' },
      { name: 'Moradabad', region: 'Uttar Pradesh' },
      { name: 'Mumbai', region: 'Maharashtra' },
      { name: 'Mysore', region: 'Karnataka' },
      { name: 'Nagpur', region: 'Maharashtra' },
      { name: 'Nashik', region: 'Maharashtra' },
      { name: 'Navi Mumbai', region: 'Maharashtra' },
      { name: 'Noida', region: 'Uttar Pradesh' },
      { name: 'Ongole', region: 'Andhra Pradesh' },
      { name: 'Patiala', region: 'Punjab' },
      { name: 'Patna', region: 'Bihar' },
      { name: 'Pondicherry', region: 'Puducherry' },
      { name: 'Pune', region: 'Maharashtra' },
      { name: 'Raipur', region: 'Chhattisgarh' },
      { name: 'Rajkot', region: 'Gujarat' },
      { name: 'Rajahmundry', region: 'Andhra Pradesh' },
      { name: 'Ranchi', region: 'Jharkhand' },
      { name: 'Rohtak', region: 'Haryana' },
      { name: 'Salem', region: 'Tamil Nadu' },
      { name: 'Sangli', region: 'Maharashtra' },
      { name: 'Shimla', region: 'Himachal Pradesh' },
      { name: 'Siliguri', region: 'West Bengal' },
      { name: 'Solapur', region: 'Maharashtra' },
      { name: 'Srinagar', region: 'Jammu & Kashmir' },
      { name: 'Surat', region: 'Gujarat' },
      { name: 'Thane', region: 'Maharashtra' },
      { name: 'Thiruvananthapuram', region: 'Kerala' },
      { name: 'Thrissur', region: 'Kerala' },
      { name: 'Tiruchirapalli', region: 'Tamil Nadu' },
      { name: 'Tirunelveli', region: 'Tamil Nadu' },
      { name: 'Udaipur', region: 'Rajasthan' },
      { name: 'Ujjain', region: 'Madhya Pradesh' },
      { name: 'Vadodara', region: 'Gujarat' },
      { name: 'Varanasi', region: 'Uttar Pradesh' },
      { name: 'Vijayawada', region: 'Andhra Pradesh' },
      { name: 'Visakhapatnam', region: 'Andhra Pradesh' },
      { name: 'Warangal', region: 'Telangana' },
      { name: 'Yamunanagar', region: 'Haryana' },
    ],
  },
  ae: {
    popularCities: [
      'Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman',
      'Ras Al Khaimah', 'Fujairah', 'Al Ain', 'Umm Al Quwain',
    ],
    allCities: [
      { name: 'Abu Dhabi', region: 'Abu Dhabi' },
      { name: 'Ajman', region: 'Ajman' },
      { name: 'Al Ain', region: 'Abu Dhabi' },
      { name: 'Al Fujairah', region: 'Fujairah' },
      { name: 'Al Quoz', region: 'Dubai' },
      { name: 'Business Bay', region: 'Dubai' },
      { name: 'Bur Dubai', region: 'Dubai' },
      { name: 'Deira', region: 'Dubai' },
      { name: 'Downtown Dubai', region: 'Dubai' },
      { name: 'Dubai', region: 'Dubai' },
      { name: 'Dubai Marina', region: 'Dubai' },
      { name: 'Dubai Silicon Oasis', region: 'Dubai' },
      { name: 'Fujairah', region: 'Fujairah' },
      { name: 'International City', region: 'Dubai' },
      { name: 'Jumeirah', region: 'Dubai' },
      { name: 'Khalifa City', region: 'Abu Dhabi' },
      { name: 'Mirdif', region: 'Dubai' },
      { name: 'Musaffah', region: 'Abu Dhabi' },
      { name: 'Palm Jumeirah', region: 'Dubai' },
      { name: 'Ras Al Khaimah', region: 'Ras Al Khaimah' },
      { name: 'Sharjah', region: 'Sharjah' },
      { name: 'Umm Al Quwain', region: 'Umm Al Quwain' },
    ],
  },
}

export const DEFAULT_COUNTRY = 'in'
